FROM ubuntu:latest

# RUN apt-get update && apt-get install -y python3
# RUN apt-get install openjdk-17-jre -y
# RUN apt-get install pip -y


# # Set environment variables
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# # Set the working directory in the container
# WORKDIR /code

# # Install dependencies
# COPY requirements.txt /code/
# RUN pip install --no-cache-dir -r requirements.txt

# # Copy the current directory contents into the container at /code
# COPY . .

# CMD "spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1 Spark_Filtering.py"
# # CMD "spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1 new_spark.py"

